import React, { useMemo, useState } from 'react';
import { Pressable, Text, View, StyleSheet } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { ZahradaStackParamList } from '../navigation/types';
import { Screen, Card, TextField, PrimaryButton, SectionTitle, HelperNote, colors } from '../components/ui';
import ConfirmDialog from '../components/ConfirmDialog';
import { DateField } from '../components/DatePicker';
import { useAppData } from '../context/AppDataContext';
import { useSingleSubmit } from '../utils/useSingleSubmit';
import { SEED_PLANT_SPECIES } from '../data/seedPlants';
import { checkCropRotation, checkCompanionPlanting } from '../rules/cropRotation';
import { getTaskTemplates } from '../data/taskTemplates';
import { DIFFICULTY_LABEL, formatDate } from '../utils/format';
import { EARLINESS_LABEL, EarlinessGroup, PlantSpecies } from '../types';

type Props = NativeStackScreenProps<ZahradaStackParamList, 'AddPlant'>;

// Jen pár ukázkových odrůd pro placeholder v poli - ne reálný seznam k výběru.
const VARIETY_PLACEHOLDER: Record<string, string> = {
  rajce: 'Cherry, Roma, Volovské srdce',
  okurka_salatovka: 'Sandra, Daniela',
  okurka_nakladacka: 'Vega, Regina',
  jahody: 'Elsanta, Malwina',
  brambory: 'Rosara, Adéla',
};

const EARLINESS_OPTIONS: EarlinessGroup[] = ['rana', 'polorana', 'pozdni'];

interface PendingPlanting {
  species: PlantSpecies;
  plantedDate: Date;
  variety: string;
  earliness?: EarlinessGroup;
}

export default function AddPlantScreen({ route, navigation }: Props) {
  const { bedId } = route.params;
  const { garden, bedHistory, addPlanting, addTask } = useAppData();
  const [selected, setSelected] = useState<PlantSpecies | null>(null);
  const [plantedDate, setPlantedDate] = useState(new Date());
  const [variety, setVariety] = useState('');
  const [earliness, setEarliness] = useState<EarlinessGroup | undefined>(undefined);
  const [warning, setWarning] = useState<{ pending: PendingPlanting; message: string } | null>(null);
  const [autoTasksNotice, setAutoTasksNotice] = useState<string | null>(null);

  const history = bedHistory(bedId);
  const currentlyGrowingIds = useMemo(
    () => Array.from(new Set(history.map((p) => p.speciesId))),
    [history]
  );

  const commitPlanting = useSingleSubmit(async (pending: PendingPlanting) => {
    await addPlanting({
      bedId,
      speciesId: pending.species.id,
      plantedAt: pending.plantedDate.toISOString(),
      year: pending.plantedDate.getFullYear(),
      status: 'roste',
      variety: pending.variety.trim() || undefined,
      varietyEarliness: pending.earliness,
    });

    const templates = getTaskTemplates(pending.species.id);
    if (templates.length > 0) {
      const createdTitles: string[] = [];
      for (const tpl of templates) {
        const due = new Date(pending.plantedDate);
        due.setDate(due.getDate() + tpl.offsetDays);
        await addTask({
          gardenId: garden?.id ?? '',
          bedIds: [bedId],
          treeIds: [],
          title: tpl.title,
          type: tpl.type,
          dueDate: due.toISOString(),
          autoGenerated: true,
        });
        createdTitles.push(`${tpl.title} (${formatDate(due.toISOString())})`);
      }
      setAutoTasksNotice(
        `🌱 ${pending.species.name} je v záhonu! Appka rovnou navrhla podle běžných agrolhůt i tyto úkoly v Kalendáři:\n\n${createdTitles.join('\n')}`
      );
    } else {
      navigation.goBack();
    }
  });

  const handleAdd = () => {
    if (!selected) return;
    const pending: PendingPlanting = { species: selected, plantedDate, variety, earliness };

    const rotationWarnings = checkCropRotation(history, selected, plantedDate.getFullYear());
    const companionWarnings = checkCompanionPlanting(selected, currentlyGrowingIds);

    const allMessages = [
      ...rotationWarnings.map((w) => w.message),
      ...companionWarnings.map(
        (w) => `${selected.name} a ${w.otherSpeciesName} si nesvědčí: ${w.reason}`
      ),
    ];

    if (allMessages.length === 0) {
      commitPlanting(pending);
      return;
    }

    setWarning({ pending, message: allMessages.join('\n\n') });
  };

  return (
    <Screen>
      <SectionTitle>Vybrat rostlinu</SectionTitle>
      <View style={styles.grid}>
        {SEED_PLANT_SPECIES.map((sp) => (
          <Pressable
            key={sp.id}
            onPress={() => {
              setSelected(sp);
              setVariety('');
              setEarliness(undefined);
            }}
            style={[styles.chip, selected?.id === sp.id && styles.chipActive]}
          >
            <Text style={[styles.chipText, selected?.id === sp.id && styles.chipTextActive]}>
              {sp.name}
            </Text>
          </Pressable>
        ))}
      </View>

      {selected && (
        <Card style={{ marginTop: 16 }}>
          <Text style={styles.detailTitle}>{selected.name}</Text>
          <Text style={styles.detailMeta}>{DIFFICULTY_LABEL[selected.difficultyGroup]}</Text>
          <Text style={styles.detailMeta}>Světlo: {selected.lightNeeds}</Text>
          <Text style={styles.detailMeta}>Voda: {selected.waterNeeds}</Text>
          <TextField
            label="Odrůda (volitelné)"
            value={variety}
            onChangeText={setVariety}
            placeholder={`např. ${VARIETY_PLACEHOLDER[selected.id] ?? 'konkrétní odrůda'}`}
          />
          <Text style={styles.smallLabel}>Ranost odrůdy (volitelné)</Text>
          <View style={styles.chipRow}>
            {EARLINESS_OPTIONS.map((e) => (
              <Pressable
                key={e}
                onPress={() => setEarliness(earliness === e ? undefined : e)}
                style={[styles.smallChip, earliness === e && styles.chipActive]}
              >
                <Text style={[styles.chipText, earliness === e && styles.chipTextActive]}>
                  {EARLINESS_LABEL[e]}
                </Text>
              </Pressable>
            ))}
          </View>
          <HelperNote>Odrůda i ranost se zatím píší/vybírají ručně - výběr ze seznamu odrůd appka nabídne v budoucí verzi.</HelperNote>
          <DateField label="Datum vysazení" required value={plantedDate} onChange={setPlantedDate} />
          <PrimaryButton title="Přidat rostlinu do záhonu" onPress={handleAdd} />
        </Card>
      )}

      <ConfirmDialog
        visible={!!warning}
        title="Upozornění před přidáním"
        message={warning?.message ?? ''}
        cancelText="Zrušit"
        confirmText="Přesto přidat"
        onCancel={() => setWarning(null)}
        onConfirm={() => {
          if (warning) commitPlanting(warning.pending);
          setWarning(null);
        }}
      />

      <ConfirmDialog
        visible={!!autoTasksNotice}
        title="Navazující úkoly"
        message={autoTasksNotice ?? ''}
        confirmText="OK"
        onConfirm={() => {
          setAutoTasksNotice(null);
          navigation.goBack();
        }}
      />
    </Screen>
  );
}

const styles = StyleSheet.create({
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  smallChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 4 },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { color: colors.text, fontWeight: '600' },
  chipTextActive: { color: 'white' },
  detailTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
  detailMeta: { fontSize: 13, color: colors.textMuted, marginTop: 4, marginBottom: 8 },
  smallLabel: { fontSize: 13, fontWeight: '600', color: colors.text, marginBottom: 6 },
});
