// Datový model appky Ekozahrádka (V1 MVP podmnožina dle sekce 4 specifikace).
// V1 pracuje jen s jednou zahradou a jedním lokálním uživatelem (bez sdílení a účtů).

export type ExperienceLevel = 'zacatecnik' | 'stredne_pokrocily' | 'pokrocily';

export interface Profile {
  name: string;
  email: string;
  experienceLevel: ExperienceLevel;
}

export interface Garden {
  id: string;
  name: string;
  location: string;
  elevation?: string;
  orientation?: string;
  slope?: string;
  createdAt: string;
}

export type BedType = 'zeleninovy' | 'bylinkovy' | 'kvetinovy' | 'jiny';

export interface Bed {
  id: string;
  gardenId: string;
  name: string;
  type: BedType;
  foundedAt: string; // založeno
  photoUri?: string;
  lastEditedBy?: string;
  lastEditedAt?: string;
}

export type TreeCategory = 'ovocny' | 'okrasny';

export type EarlinessGroup = 'rana' | 'polorana' | 'pozdni';

export const EARLINESS_LABEL: Record<EarlinessGroup, string> = {
  rana: 'Raná',
  polorana: 'Poloraná',
  pozdni: 'Pozdní',
};

export interface Tree {
  id: string;
  gardenId: string;
  name: string;
  category: TreeCategory;
  rootstockType?: string; // typ podnože
  plantedAt: string;
  location?: string;
  status?: string;
  note?: string;
  variety?: string; // odrůda - zatím volný text, do budoucna výběr z nabídky
  varietyEarliness?: EarlinessGroup;
  photoUri?: string;
  lastEditedBy?: string;
  lastEditedAt?: string;
}

export type DifficultyGroup = 'narocna' | 'stredne_narocna' | 'mene_narocna' | 'luskovina';

export const DIFFICULTY_GROUP_LABEL: Record<DifficultyGroup, string> = {
  narocna: 'Náročná',
  stredne_narocna: 'Středně náročná',
  mene_narocna: 'Méně náročná',
  luskovina: 'Luskovina (obohacuje půdu)',
};

export interface BadCompanion {
  speciesId: string;
  reason: string;
}

export type SpeciesCategory = 'zelenina' | 'bylinka' | 'kvetina';

export const SPECIES_CATEGORY_LABEL: Record<SpeciesCategory, string> = {
  zelenina: 'Zelenina',
  bylinka: 'Bylinky',
  kvetina: 'Květiny',
};

export interface PlantSpecies {
  id: string;
  name: string;
  category: SpeciesCategory;
  difficultyGroup: DifficultyGroup;
  lightNeeds: string;
  waterNeeds: string;
  goodCompanions: string[]; // ids druhů
  badCompanions: BadCompanion[];
  commonMistakes: string;
  source: string;
  verifiedBy?: string;
  verifiedAt?: string;
}

export interface PlantingRecord {
  id: string;
  bedId: string;
  speciesId: string;
  plantedAt: string; // skutečné datum vysazení vybrané v kalendáři
  year: number; // odvozeno z plantedAt - pro kontrolu opakování v osevním postupu
  status: string;
  variety?: string; // odrůda - zatím volný text, do budoucna výběr z nabídky
  varietyEarliness?: EarlinessGroup;
  note?: string;
}

export type TaskType = 'zaliti' | 'hnojeni' | 'sklizen' | 'orez' | 'ochrana' | 'jine';

export interface Task {
  id: string;
  gardenId: string;
  bedIds: string[];
  treeIds: string[];
  title: string;
  type: TaskType;
  dueDate: string;
  done: boolean;
  doneBy?: string;
  doneAt?: string;
  weatherAdjusted?: boolean;
  adjustReason?: string;
  autoGenerated?: boolean; // navrženo appkou dle agrolhůt (prototyp), ne ručně zadáno
  plantingId?: string; // u autoGenerated úkolů - konkrétní rostlina v záhonu, ze které úkol vznikl
  lastEditedBy?: string;
  lastEditedAt?: string;
}

export interface JournalEntry {
  id: string;
  bedId?: string;
  treeId?: string;
  date: string;
  text: string;
  photoUri?: string;
  lastEditedBy: string;
  lastEditedAt: string;
}

export interface Harvest {
  id: string;
  gardenId: string;
  bedId?: string;
  treeId?: string;
  cropName: string;
  amount: number;
  unit: string;
  date: string;
}

export interface Article {
  id: string;
  title: string;
  category: string;
  content: string;
  readMinutes: number;
}
